### ISSUE TITLE
MCM pages string incorrect size

### ISSUE THREAD

**Issue by ThisIsPatrick** [darkconsole/dse-display-model#1]
The Pages String in dse_dm_QuestMCM is the incorrect size, there are 4 MCM Pages but only space for 3 is allocated:

**dse_dm_QuestMCM.psc Line 36**
```
self.Pages = new String[3]

self.Pages[0] = "$DM3_Menu_General"
self.Pages[1] = "$DM3_Menu_Stats"
self.Pages[2] = "$DM3_Menu_Info"
self.Pages[3] = "$DM3_Menu_Splash"
```

The String[] array size should be changed from 3 to 4.

**Comment by darkconsole** [comment]
thank you
