### ISSUE TITLE
Versions of ConsoleUtilSSE > 1.0.7 not recognized as valid

### ISSUE THREAD

**Issue by teutonicdude** [darkconsole/dse-display-model#6]
Steps to reproduce, using MO2:
1. Have DispMod installed, have ConsoleUtil 1.0.7 installed
2. Replace ConsoleUtil 1.0.7 with ConsoleUtil 1.1.0 or 1.2.0 using MO2 installer
3. The "you need ConsoleUtil 1.0.4 or greater" notification appears and ConsoleUtil doesn't show up as available in the MCM.
4. Reinstall ConsoleUtil 1.0.7 as per step 2.
5. notification does not appear and ConsoleUtil shows up as available in the MCM

EDIT: Disregard, SKSE is disabling the newer versions of ConsoleUtil for some reason.
EDITEDIT: Turns out ConsoleUtil, among a few other mods, now has this mod as a requirement:
https://www.nexusmods.com/skyrimspecialedition/mods/32444

**Comment by teutonicdude** [comment]
EDIT: Disregard, SKSE is disabling the newer versions of ConsoleUtil for some reason.
EDITEDIT: Turns out ConsoleUtil, among a few other mods, now has this mod as a requirement:
https://www.nexusmods.com/skyrimspecialedition/mods/32444

**Comment by ThelenAi** [comment]
I used nemesis for this mod and it works fine. The issue with nemesis is that it doesn't support creatures. As long as the mod doesn't animate those it should be fine in my experience
