### ISSUE TITLE
Using furniture on non-followers

### ISSUE THREAD

**Issue by teutonicdude** [darkconsole/dse-display-model#7]
Not sure if this counts as a bad interaction between mods or a bug, but ran into an issue with using paradise halls slaves and furniture. That said, it appears this bug would also come up with other "non-follower" followers hence the report.

If you have slave of either the regular or Home Sweet Home variety assigned to furniture, then release them using the talk to dialog options, they keep following you regardless of any commands you give them. Probably due to being assigned to the display model follow faction and package and there wasn't a way to turn it off (no DM3 dialog options) that I could find.

A workaround solution is to re-assign them to furniture and then use the "reload" function in the furniture menu. This releases them without assigning them the follow faction and package.

**Comment by darkconsole** [comment]
this commit which will finally be in the next release will not require the book in your inventory to tell them to go away

```
commit a243df64bf45740242ebccb62f50da700300a8eb
Author: darkconsole <darkcee.legit@gmail.com>
Date:   Sun Oct 18 20:34:56 2020 -0500

    dont require book to tell them to fuck off
```
